#!/bin/sh
#
# chkconfig: 35 86 15
# description: PostgreSQL

PGACCOUNT="pgsql"
PGDATA="/usr/local/pgsql_data"
PGLIB="/usr/local/pgsql/lib"
PG_CTL="/usr/local/pgsql/bin/pg_ctl"
PGLOG="/usr/local/pgsql/postgresql.log"

. /etc/rc.d/init.d/functions

case "$1" in
    start)
        echo -n "Starting postgres: "
        su - $PGACCOUNT -c "$PG_CTL -D \
            $PGDATA -o \"-i\" -l $PGLOG start"
        ;;
    stop)
        echo -n "Stopping postgres: "
        su - $PGACCOUNT -c "$PG_CTL -D $PGDATA stop"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
